name: "Docker Build and Push"

on:
  workflow_call:
    inputs:
      registry:
        description: 'OCI registry (e.g. ghcr.io or docker.io)'
        required: true
        type: string
      username:
        description: 'Registry username'
        required: true
        type: string
      image_name:
        description: 'Image name'
        required: true
        type: string
      tags:
        description: 'Comma-separated tags'
        required: false
        type: string
        default: 'latest'
      context:
        description: 'Build context'
        required: false
        type: string
        default: '.'
      dockerfile:
        description: 'Path to Dockerfile'
        required: false
        type: string
        default: 'Dockerfile'
    secrets:
      REGISTRY_TOKEN:
        description: 'Registry token'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.username }}/${{ inputs.image_name }}:${{ inputs.tags }}
